### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by abazanov** [alexbeletsky/elmah-mvc#79]
Hi Guys! I tried tonight to get this elmah.mvc from the nuget working and could not. I installed the package and add the appSettings ok. got it working on localhost. But when i pushed it to Azure, it would not work. I scoured the whole Google on how to get it to do remoteAccess and all the suggestions were ending in error because my web.config was malformed. 

I would be very thankful if someone could point me to a example configuration file where it has all teh options:
1 - enabling remoteAccess
2 - specifying where to save the log
3 - setting up email notifications

For now, just gave up and uninstalled it :(
Thanks!

**Comment by issafram** [comment]
You mentioned that your web.config is malformed.  That is your first problem.
That needs to be fixed.
Do you at least have your web.config?  Usually the error in .NET will tell you the specific error.

**Comment by cocojiambo** [comment]
hi @issafram thanks for taking the time to respond. my web.config is fine, it is just that when i try to add the elmah configurations to it that it becomes malformed. and that is because i do not know how they should be added. so i was asking for some documentation on how i can add them, all the sections and everything. 

thanks
